### ISSUE TITLE
ImportError:

### ISSUE THREAD

**Issue by Limbicnation** [magenta/music-spectrogram-diffusion#15] opened 2023-02-01 19:32 UTC
Hi, I got this error using colab.
`ImportError: cannot import name 'optim' from 'flax' (/usr/local/lib/python3.8/dist-packages/flax/__init__.py)`

**Comment by cghawthorne** [comment] 2023-02-01 22:51
Duplicate of #14 14

**Closed by cghawthorne** 2023-02-01 22:51 UTC
